### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by youth123** [laekov/fastmoe#67]
**Describe the bug**
Failed to build fastmoe in the docker images that megatron provides.
https://ngc.nvidia.com/catalog/containers/nvidia:pytorch

**To Reproduce**
USE_NCCL=1 python setup.py install
**Expected behavior**
Installed successfully.
**Logs**
FAILED: /root/paddlejob/toyer_switch/fastmoe/build/temp.linux-x86_64-3.8/cuda/global_exchange.o
error: no matching function for call to ‘HackNCCLGroup::broadcastUniqueNCCLID(ncclUniqueId*)’                                                                      
   91 |         broadcastUniqueNCCLID(&ncclID);
**Platform**
 - Device: NVIDIA V100
 - OS:Ubuntu
 - CUDA version: 11.1
- NCCL version: 2.8.3

**Comment by youth123** [comment]
when I git reset --hard b861e928000ddf1a94bb5f795e6286769e743bd9, it can be installed successfully.
But it failed in 9170835c24a691489086c73f95a6fde201589147, maybe some commit between these commit ids caused.

**Comment by laekov** [comment]
I will look into this next week.

**Comment by laekov** [comment]
What is your PyTorch version? @youth123

**Comment by youth123** [comment]
> What is your PyTorch version? @youth123

1.8.0

**Comment by laekov** [comment]
So, the difference is that we check pytorch's version using its macros [here](https://github.com/laekov/fastmoe/blob/master/cuda/global_exchange.cpp#L84) in order to be compatible to older PyTorch versions. 
Can you check if your pytorch header files correctly define these macros?

**Comment by youth123** [comment]
Sorry to reply so late. My pytorch header files don't have TORCH_VERSION_MAJOR.

**Comment by laekov** [comment]
The macro is defined [here](https://github.com/pytorch/pytorch/blob/v1.8.0/torch/csrc/api/include/torch/version.h.in) in PyTorch 1.8.0. Its absense indicates that your PyTorch may be incorrectly installed.

**Comment by superqing001** [comment]
> **Describe the bug** Failed to build fastmoe in the docker images that megatron provides. https://ngc.nvidia.com/catalog/containers/nvidia:pytorch
> 
> **To Reproduce** Steps to reproduce the behavior: USE_NCCL=1 python setup.py install **Expected behavior** Installed successfully. **Logs** FAILED: /root/paddlejob/toyer_switch/fastmoe/build/temp.linux-x86_64-3.8/cuda/global_exchange.o error: no matching function for call to ‘HackNCCLGroup::broadcastUniqueNCCLID(ncclUniqueId*)’ 91 | broadcastUniqueNCCLID(&ncclID); **Platform**
> 
> * Device: NVIDIA V100
> * OS:Ubuntu
> * CUDA version: 11.1
> * NCCL version: 2.8.3

I also encountered this problem. How did you solve it?
